<?php

// Language definitions used in admin_users.php
$lang_admin_users = array(

'Non numeric message'		=>	'आपने केवल संख्यात्मक स्तंभ में गैर-संख्यात्मक मान दर्ज किया है।',
'Invalid date time message'	=>	'आपने अमान्य तिथि/समय दर्ज किया है।',
'Not verified'				=>	'असत्यापित',

// Actions: mass delete/ban etc.
'No users selected'			=>	'कोई उपयोगकर्ता चयनित नहीं है।',
'No move admins message'	=>	'सुरक्षा कारणों से, आपको एक समूह से दूसरे समूह में कई प्रशासकों को स्थानांतरित करने की अनुमति नहीं है। यदि आप इन प्रशासकों को स्थानांतरित करना चाहते हैं, तो उनके संबंधित उपयोगकर्ता प्रोफ़ाइल पर कर सकते हैं।',
'No delete admins message'	=>	'प्रशासकों को हटाया नहीं जा सकता। प्रशासकों को हटाने के लिए, उन्हें पहले एक अन्य उपयोगकर्ता समूह में स्थानांतरित करना आवश्यक है।',
'No ban admins message'		=>	'प्रशासकों पर प्रतिबंध नहीं लगाया जा सकता। प्रशासकों पर प्रतिबंध लगाने के लिए, उन्हें पहले एक अन्य उपयोगकर्ता समूह में स्थानांतरित करना आवश्यक है।',
'No ban mods message'		=>	'मॉडरेटर्स पर प्रतिबंध नहीं लगाया जा सकता। मॉडरेटर्स पर प्रतिबंध लगाने के लिए, उन्हें पहले एक अन्य उपयोगकर्ता समूह में स्थानांतरित करना आवश्यक है।',
'Move users'				=>	'उपयोगकर्ता समूह बदलें',
'Move users subhead'		=>	'नया उपयोगकर्ता समूह चुनें',
'New group label'			=>	'नया समूह',
'New group help'			=>	'चयनित उपयोगकर्ताओं को स्थानांतरित करने के लिए समूह चुनें। सुरक्षा कारणों से, एकाधिक उपयोगकर्ताओं को प्रशासक समूह में स्थानांतरित करना संभव नहीं है।',
'Invalid group message'		=>	'अमान्य समूह ID।',
'Users move redirect'		=>	'उपयोगकर्ता समूह बदल दिया गया। पुनर्निर्देशित किया जा रहा है...',
'Delete users'				=>	'उपयोगकर्ता हटाएँ',
'Confirm delete legend'		=>	'महत्वपूर्ण: हटाने से पहले पढ़ें',
'Confirm delete info'		=>	'कृपया पुष्टि करें कि आप इन उपयोगकर्ताओं को हटाना चाहते हैं।',
'Delete posts'				=>	'इन उपयोगकर्ताओं द्वारा बनाए गए सभी पोस्ट और विषय हटा दें।',
'Delete warning'			=>	'<strong>चेतावनी!</strong> हटाए गए उपयोगकर्ताओं/पोस्टों को पुनर्स्थापित नहीं किया जा सकता। यदि आप इन उपयोगकर्ताओं द्वारा बनाई गई पोस्टों को हटाना नहीं चाहते, तो भविष्य में उन्हें मैन्युअल रूप से हटाया जा सकता है।',
'Users delete redirect'		=>	'उपयोगकर्ता हटाए गए। पुनर्निर्देशित किया जा रहा है...',
'Ban users'					=>	'उपयोगकर्ताओं पर प्रतिबंध लगाएँ',
'Message expiry subhead'	=>	'प्रतिबंध संदेश और समाप्ति',
'Ban message label'			=>	'प्रतिबंध संदेश',
'Ban message help'			=>	'एक संदेश जो प्रतिबंधित उपयोगकर्ताओं को फ़ोरम पर आने पर प्रदर्शित होगा।',
'Expire date label'			=>	'समाप्ति तिथि',
'Expire date help'			=>	'तिथि जब यह प्रतिबंध स्वचालित रूप से हटा दिया जाएगा (प्रारूप: yyyy-mm-dd)। मैन्युअल रूप से हटाने के लिए खाली छोड़ें।',
'Ban IP label'				=>	'आईपी पते पर प्रतिबंध लगाएँ',
'Ban IP help'				=>	'इन उपयोगकर्ताओं के आईपी पते पर भी प्रतिबंध लगाएँ ताकि उन्हें नया खाता बनाना मुश्किल हो जाए।',
'Invalid date message'		=>	'आपने अमान्य समाप्ति तिथि दर्ज की है।',
'Invalid date reasons'		=>	'प्रारूप YYYY-MM-DD होना चाहिए और तिथि कम से कम एक दिन भविष्य की होनी चाहिए।',
'Users banned redirect'		=>	'उपयोगकर्ताओं पर प्रतिबंध लगाया गया। पुनर्निर्देशित किया जा रहा है...',

'User search head'			=>	'उपयोगकर्ता खोज',
'User search subhead'		=>	'खोज मापदंड दर्ज करें',
'User search info'			=>	'डेटाबेस में उपयोगकर्ताओं की खोज करें। आप खोज के लिए एक या अधिक शर्तें दर्ज कर सकते हैं। तारांकन (*) के रूप में वाइल्डकार्ड स्वीकार्य हैं।',
'Username label'			=>	'उपयोगकर्ता नाम',
'E-mail address label'		=>	'ईमेल पता',
'Title label'				=>	'शीर्षक',
'Real name label'			=>	'वास्तविक नाम',
'Website label'				=>	'वेबसाइट',
'Jabber label'				=>	'जैबर',
'ICQ label'					=>	'आईसीक्यू',
'Location label'			=>	'स्थान',
'Signature label'			=>	'हस्ताक्षर',
'Admin note label'			=>	'प्रशासक टिप्पणी',
'Posts more than label'		=>	'पोस्टों की संख्या से अधिक',
'Posts less than label'		=>	'पोस्टों की संख्या से कम',
'Last post after label'		=>	'अंतिम पोस्ट तिथि के बाद',
'Date help'					=>	'(yyyy-mm-dd hh:mm:ss)',
'Last post before label'		=>	'अंतिम पोस्ट तिथि के पहले',
'Last visit after label'		=>	'अंतिम आगमन के बाद',
'Last visit before label'	=>	'अंतिम आगमन के पहले',
'Registered after label'		=>	'पंजीकृत तिथि के बाद',
'Registered before label'	=>	'पंजीकृत तिथि के पहले',
'Order by label'			=>	'क्रमबद्ध करें:',
'Order by username'			=>	'उपयोगकर्ता नाम',
'Order by e-mail'			=>	'ईमेल',
'Order by posts'			=>	'पोस्टों की संख्या',
'Order by last post'		=>	'अंतिम पोस्ट',
'Order by last visit'		=>	'अंतिम आगमन',
'Order by registered'		=>	'पंजीकरण तिथि',
'Ascending'					=>	'आरोही',
'Descending'				=>	'अवरोही',
'User group label'			=>	'उपयोगकर्ता समूह',
'All groups'				=>	'सभी समूह',
'Unverified users'			=>	'असत्यापित उपयोगकर्ता',
'Submit search'				=>	'खोज प्रस्तुत करें',

'IP search head'			=>	'आईपी खोज',
'IP search subhead'			=>	'आईपी खोज के लिए दर्ज करें',
'IP address label'			=>	'आईपी पता',
'IP address help'			=>	'पोस्ट डेटाबेस में खोजने के लिए आईपी पता।',
'Find IP address'			=>	'आईपी पता खोजें',

'Results head'				=>	'खोज परिणाम',
'Results username head'		=>	'उपयोगकर्ता नाम',
'Results e-mail head'		=>	'ईमेल',
'Results title head'		=>	'शीर्षक/स्थिति',
'Results posts head'		=>	'पोस्टें',
'Results admin note head'	=>	'प्रशासक टिप्पणी',
'Results actions head'		=>	'क्रियाएँ',
'Results IP address head'	=>	'आईपी पता',
'Results last used head'	=>	'अंतिम उपयोग',
'Results times found head'	=>	'खोज की गई संख्या',
'Results action head'		=>	'क्रिया',
'Results find more link'	=>	'इस आईपी के लिए अधिक उपयोगकर्ता खोजें',
'Results no posts found'	=>	'फ़िलहाल इस उपयोगकर्ता द्वारा फ़ोरम में कोई पोस्ट नहीं है।',
'Select'					=>	'चुनें',
'Select all'				=>	'सभी चुनें',
'Unselect all'				=>	'सभी अचयनित करें',
'Ban'						=>	'प्रतिबंध',
'Delete'					=>	'हटाएँ',
'Change group'				=>	'समूह बदलें',
'Bad IP message'			=>	'दर्ज किया गया आईपी पता सही प्रारूप में नहीं है।',
'Results view IP link'		=>	'आईपी सांख्यिकी देखें',
'Results show posts link'	=>	'पोस्ट दिखाएँ',
'Results guest'				=>	'अतिथि',
'Results no IP found'		=>	'डेटाबेस में दर्ज किया गया आईपी पता नहीं मिला।',
'No match'					=>	'कोई मेल नहीं',

);