<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'User search'						=>	'उपयोगकर्ता खोज',
'No search permission'				=>	'आपको खोज विशेषता का उपयोग करने की अनुमति नहीं है।',
'Search flood'						=>	'खोज के बीच कम से कम %s सेकंड का अंतर होना चाहिए। कृपया %s सेकंड प्रतीक्षा करें और पुनः प्रयास करें।',
'Search'							=>	'खोजें',
'Search criteria legend'			=>	'खोज मापदंड दर्ज करें',
'Search info'						=>	'कीवर्ड से खोजने के लिए, आपको एक या अधिक शब्द दर्ज करने होंगे। शब्दों को स्पेस से अलग करें। AND, OR और NOT का उपयोग खोज को सुधारने के लिए करें। लेखक द्वारा खोजने के लिए, उस उपयोगकर्ता नाम को दर्ज करें जिसके पोस्ट खोजना चाहते हैं। आंशिक मिलान के लिए वाइल्डकार्ड * का उपयोग करें।',
'Keyword search'					=>	'कीवर्ड से खोज',
'Author search'						=>	'लेखक से खोज',
'Search in legend'					=>	'खोज कहाँ करें',
'Search in info'					=>	'चयनित फ़ोरम में खोजें और यह चुनें कि आप विषय शीर्षक, पोस्ट टेक्स्ट या दोनों में खोजना चाहते हैं।',
'Search multiple forums info'		=>	'यदि कोई फ़ोरम चयनित नहीं है, तो सभी फ़ोरम में खोज करें।',
'Forum search'						=>	'फ़ोरम',
'Search in'							=>	'खोज में',
'Message and subject'				=>	'पोस्ट टेक्स्ट और विषय शीर्षक',
'Message only'						=>	'केवल पोस्ट टेक्स्ट',
'Topic only'						=>	'केवल विषय शीर्षक',
'Sort by'							=>	'के अनुसार क्रमबद्ध करें',
'Sort order'						=>	'क्रमबद्ध आदेश',
'Search results legend'				=>	'खोज परिणाम कैसे देखें',
'Search results info'				=>	'आप यह चुन सकते हैं कि आप अपने परिणामों को कैसे क्रमबद्ध करना चाहते हैं और कैसे प्रदर्शित करना चाहते हैं।',
'Sort by post time'				=>	'पोस्ट समय',
'Sort by author'					=>	'लेखक',
'Sort by subject'					=>	'विषय',
'Sort by forum'						=>	'फ़ोरम',
'Ascending'							=>	'आरोही',
'Descending'						=>	'अवरोही',
'Show as'							=>	'इस रूप में दिखाएँ',
'Show as topics'					=>	'विषय',
'Show as posts'						=>	'पोस्टें',

// Results
'Search'							=>	'खोज',
'Search results'					=>	'खोज परिणाम',
'Quick search show_new'				=>	'नए',
'Quick search show_recent'			=>	'सक्रिय',
'Quick search show_unanswered'		=>	'बिना उत्तर के',
'Quick search show_replies'			=>	'पोस्ट किए',
'Quick search show_user_topics'		=>	'%s द्वारा विषय',
'Quick search show_user_posts'		=>	'%s द्वारा पोस्टें',
'Quick search show_subscriptions'	=>	'%s की सदस्यता',
'Quick search show_user_warn' => '%s के लिए चेतावनी',
'By keywords show as topics'		=>	'शब्द "%s" वाले विषय',
'By keywords show as posts'			=>	'शब्द "%s" वाली पोस्टें',
'By user show as topics'			=>	'%s द्वारा पोस्ट वाले विषय',
'By user show as posts'				=>	'%s द्वारा पोस्टें',
'By both show as topics'			=>	'शब्द "%s" वाले विषय, %s द्वारा',
'By both show as posts'				=>	'शब्द "%s" वाली पोस्टें, %s द्वारा',
'No terms'							=>	'आपको कम से कम एक कीवर्ड और/या लेखक दर्ज करना आवश्यक है। कीवर्ड कम से कम तीन वर्णों का होना चाहिए।',
'No hits'							=>	'आपकी खोज में कोई मेल नहीं हुआ।',
'No user posts'						=>	'इस फ़ोरम में इस उपयोगकर्ता की कोई पोस्ट नहीं है।',
'No user topics'					=>	'इस फ़ोरम में इस उपयोगकर्ता का कोई विषय नहीं है।',
'No subscriptions'				=>	'इस उपयोगकर्ता के पास वर्तमान में कोई सदस्यता नहीं है।',
'No new posts'						=>	'आपके अंतिम आगमन के बाद कोई नया विषय नहीं है।',
'No recent posts'					=>	'पिछले 24 घंटों में कोई नई पोस्ट नहीं हुई।',
'No unanswered'						=>	'इस फ़ोरम में कोई बिना उत्तर वाली पोस्ट नहीं है।',
'Go to post'						=>	'पोस्ट पर जाएँ',
'Go to topic'						=>	'विषय पर जाएँ'

);